
const quotes = [
    "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
"The secret of getting ahead is getting started. – Mark Twain",
"I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. – Jimmy Dean",
"Whether you think you can or you think you can’t, you’re right. – Henry Ford",
"Act as if what you do makes a difference. It does. – William James",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
"Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
"Opportunities don't happen. You create them. – Chris Grosser",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
"Believe you can and you're halfway there. – Theodore Roosevelt",
"The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
"Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
"Dream big and dare to fail. – Norman Vaughan",
"It always seems impossible until it’s done. – Nelson Mandela",
"The purpose of our lives is to be happy. – Dalai Lama",
"Don't count the days, make the days count. – Muhammad Ali",
"The best revenge is massive success. – Frank Sinatra",
"You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy",
"What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
"Everything you’ve ever wanted is on the other side of fear. – George Addair",
"Believe in yourself and all that you are. – Christian D. Larson",
"Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
"If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. – Sheryl Sandberg",
"The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",  
"If you opportunity doesn’t knock, build a door. – Milton Berle",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon",
"Fall seven times and stand up eight. – Japanese Proverb",
"Everything has beauty, but not everyone can see. – Confucius",
"The harder you work for something, the greater you'll feel when you achieve it. – Anonymous",
"Don’t stop when you’re tired. Stop when you’re done. – Anonymous",
"Little by little, a little becomes a lot. – Tanzanian Proverb",
"Don’t wish it were easier. Wish you were better. – Jim Rohn",
"Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
"Push yourself, because no one else is going to do it for you. – Anonymous",
"Sometimes we're tested not to show our weaknesses, but to discover our strengths. – Anonymous",
"The key to success is to focus on goals, not obstacles. – Anonymous",
"Dream it. Wish it. Do it. – Anonymous",
"Success doesn't just find you. You have to go out and get it. – Anonymous",
"Don’t limit your challenges. Challenge your limits. – Anonymous",
"Sometimes later becomes never. Do it now. – Anonymous",
"Great things never come from comfort zones. – Anonymous",
"Dreams don’t work unless you do. – John C. Maxwell",
"The way to get started is to quit talking and begin doing. – Walt Disney",
"The successful warrior is the average man, with laser-like focus. – Bruce Lee",
"Don't stop until you're proud. – Anonymous",
"Work until your idols become your rivals. – Anonymous",
"Don't wait for opportunity. Create it. – George Bernard Shaw",
"Every strike brings me closer to the next home run. – Babe Ruth",
"When you arise in the morning, think of what a precious privilege it is to be alive. – Marcus Aurelius",
"Make each day your masterpiece. – John Wooden",
"Either you run the day or the day runs you. – Jim Rohn",
"Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
"Change your thoughts and you change your world. – Norman Vincent Peale",
"Your limitation—it’s only your imagination. – Anonymous",
"Don’t wish for it. Work for it. – Anonymous",
"Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
"I attribute my success to this: I never gave or took any excuse. – Florence Nightingale",
"A goal is not always meant to be reached; it often serves simply as something to aim at. – Bruce Lee",
"Keep going. Be all in. – Bryan Hutchinson",
"The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
"Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
"Life is too important to be taken seriously. – Oscar Wilde",
"Only in the darkness can you see the stars. – Martin Luther King Jr.",
"An unexamined life is not worth living. – Socrates",
"Your life does not get better by chance, it gets better by change. – Jim Rohn",
"Be yourself; everyone else is already taken. – Oscar Wilde",
"The purpose of life is a life of purpose. – Robert Byrne",
"Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
"Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
"Doubt kills more dreams than failure ever will. – Suzy Kassem",
"The difference between ordinary and extraordinary is that little extra. – Jimmy Johnson",
"Don't wait for the perfect moment, take the moment and make it perfect. – Zoey Sayward",
"Be a voice, not an echo. – Anonymous",
"Do something today that your future self will thank you for. – Unknown",
"If you want to fly, give up everything that weighs you down. – Buddha",
"Don't let yesterday take up too much of today. – Will Rogers",
"Everything you can imagine is real. – Pablo Picasso",
"Sometimes you win, sometimes you learn. – John Maxwell",
"Challenges are what make life interesting. – Anonymous",
"Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
"There are no shortcuts to any place worth going. – Beverly Sills",
"Strive not to be a success, but rather to be of value. – Albert Einstein",
"You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
"Every moment is a fresh beginning. – T.S. Eliot",
"To succeed in life, you need two things: ignorance and confidence. – Mark Twain",
"Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
"I would rather die of passion than of boredom. – Vincent van Gogh",
"The only journey is the one within. – Rainer Maria Rilke",
"Success is not measured by money or power, but by the positive impact you have on the world. – Anonymous",
"Turn your wounds into wisdom. – Oprah Winfrey",
"Don't be afraid to fail. – Anonymous",
"A diamond is merely a lump of coal that did well under pressure. – Henry Kissinger",
"The best preparation for tomorrow is doing your best today. – H. Jackson Brown Jr.",
"Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
"If you want to achieve greatness, stop asking for permission. – Anonymous",
"Keep your eyes on the stars, and your feet on the ground. – Theodore Roosevelt",
"What we think, we become. – Buddha",
"I never dreamed about success, I worked for it. – Estee Lauder",
"Perseverance is failing 19 times and succeeding the 20th. – Julie Andrews",
"When one door of happiness closes, another opens. – Helen Keller",
"Everything you do is a reflection of you. – Anonymous",
"Embrace the glorious mess that you are. – Elizabeth Gilbert",
"Difficult roads often lead to beautiful destinations. – Anonymous",
"Believe in the power of yet. – Anonymous",
"Failure is simply the opportunity to begin again, this time more intelligently. – Henry Ford",
"Hustle in silence and let your success make the noise. – Unknown",
"Dreams are the seedlings of reality. – Napoleon Hill",
"Do not be embarrassed by your failures, learn from them and start again. – Richard Branson",
"Believe in your infinite potential. – Anonymous",
"If you want to live a happy life, tie it to a goal, not to people or things. – Albert Einstein",
"Strive for progress, not perfection. – Anonymous",
"Do what is right, not what is easy nor what is popular. – Roy T. Bennett",
"The harder the battle, the sweeter the victory. – Les Brown",
"Every day is a second chance. – Anonymous",
"The only way to achieve the impossible is to believe it is possible. – Unknown",
"Success isn’t overnight. It’s when every day you get a little better than the day before. – Dwayne Johnson",
"Life shrinks or expands in proportion to one's courage. – Anaïs Nin",
"The biggest risk is not taking any risk. – Mark Zuckerberg",
"You don’t have to see the whole staircase, just take the first step. – Martin Luther King Jr.",
"If you want to be successful, you must be willing to fail. – Anonymous",
"To succeed, we must first believe that we can. – Nikos Kazantzakis",
"I never lose. I either win or learn. – Nelson Mandela",
"When nothing goes right, go left. – Unknown",
"Your passion is waiting for your courage to catch up. – Isabelle Lafleche",
"Magic is believing in yourself; if you can do that, you can make anything happen. – Johann Wolfgang von Goethe",
"Great things take time. – Anonymous",
"Keep your thoughts positive because your thoughts become your words. – Anonymous",
"A little progress each day adds up to big results. – Anonymous",
"Start where you are. Use what you have. Do what you can. – Arthur Ashe",
"Don't let success get to your head and failure to your heart. – Anonymous",
"When one door closes, another opens. – Alexander Graham Bell",
"A champion is defined not by their wins but by how they recover when they fall. – Anonymous",
"Every accomplishment starts with the decision to try. – Anonymous",
"Don't be afraid to stand for what you believe in, even if that means standing alone. – Andy Biersack",
"Life begins at the end of your comfort zone. – Neale Donald Walsch",
"Be the best version of yourself. – Anonymous",
"Your life is your message to the world. Make it inspiring. – Anonymous",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. – Jordan Belfort",
"The future depends on what you do today. – Mahatma Gandhi",
"Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi",
"Success means doing the best we can with what we have. – Zig Ziglar",
"Turn your dreams into reality by taking one step at a time. – Anonymous",
"The only way to do it is to do it. – Amelia Earhart",
"Every day is a new opportunity to change your life. – Anonymous"

    
];


module.exports = quotes;